logging:
  file: files/logs.log
  console: 1
  level: INFO
database:
  user: qglpmgcg
  base_name: qglpmgcg
  password: bsKsGrHGGRpqr4fjKbBBVXoRDj-_J6ks
  host: satao.db.elephantsql.com
  port: 5432
documents:
  sample_exemption_dir: modules/user/SampleExemption.docx
  sample_thanks_dir: modules/user/SampleThanks.docx
  directors_names:
    1: Ткаченко Ивану Сергеевичу
    2: Смелову Виталию Геннадиевичу
    4: Грисяк Анастасии Андреевне
    5: Нестерову Александру Юрьевичу
    6: Куприянову Александру Викторовичу
    7: Иванову Дмитрию Юрьевичу
    8: Безверхову Артуру Геннадьевичу
  instituts:
    1: института авиационной и ракетно-космической техники
    2: института двигателей и энергетических установок
    4: естественнонаучного института
    5: социально-гуманитарного института
    6: института информатики и кибернетики
    7: института экономики и управления
    8: юридического института